In [1]:
import numpy as np

In [21]:
def mcp(dim):     # dim-->dimension (Initialize the no. of dimensions)
    d=dim         # Store the no. of dimensions into "d".
    
    w=np.random.choice([1,1],(d))      # Initialize the weights..In MCP all the weights are equal.
    
    r=np.random.choice([0,1],(4,d))    # Initialize the value of all the dimension.
    
    e=r@w              # Dot Product the weights with dimensions.It will show the min & max Threshold value
    
    opr=input("Enter a logic operator(AND,OR): ")        # LOGIC OPERATORs
    
    print("WEIGHTS: ",w)  
    print()
    print("DIMENSION WITH (0,1): ",end="\n")
    print(r)
    print()
    print("DOT PRODUCT VALUES: ",e)
    print()

    
    if opr=="AND":
        
        t=max(e)
        print("THERSOLD: ",t)
        print()
        print("Output: ")
        print()
        
        for y in e:

            if y>=t:
                print(1) 
            else:
                print(0)
                
    elif opr=="OR":
        
        t2=min(e)
        print("THERSOLD: ",t2)
        print()
        print("Output: ")
        print()
        
        for y2 in e:
    
            if y2>t2:
                print(1) 
            else:
                print(0)
    else:
        print("SOMETHING WRONG")

In [23]:
mcp(2)

Enter a logic operator(AND,OR): AND
WEIGHTS:  [1 1]

DIMENSION WITH (0,1): 
[[1 0]
 [0 1]
 [1 1]
 [0 1]]

DOT PRODUCT VALUES:  [1 1 2 1]

THERSOLD:  2

Output: 

0
0
1
0


In [24]:
mcp(2)

Enter a logic operator(AND,OR): OR
WEIGHTS:  [1 1]

DIMENSION WITH (0,1): 
[[0 0]
 [1 1]
 [0 1]
 [1 1]]

DOT PRODUCT VALUES:  [0 2 1 2]

THERSOLD:  0

Output: 

0
1
1
1


In [28]:
mcp(3)

Enter a logic operator(AND,OR): AND
WEIGHTS:  [1 1 1]

DIMENSION WITH (0,1): 
[[1 0 1]
 [1 1 0]
 [0 1 1]
 [1 0 0]]

DOT PRODUCT VALUES:  [2 2 2 1]

THERSOLD:  2

Output: 

1
1
1
0


In [30]:
mcp(3)

Enter a logic operator(AND,OR): OR
WEIGHTS:  [1 1 1]

DIMENSION WITH (0,1): 
[[1 1 1]
 [1 1 0]
 [1 0 0]
 [0 0 0]]

DOT PRODUCT VALUES:  [3 2 1 0]

THERSOLD:  0

Output: 

1
1
1
0
